GET http://{{host}}/api/json-server/posts HTTP/1.1

### create new post - using the json-server
POST http://{{host}}/api/json-server/posts HTTP/1.1
Content-Type: application/json

{
"userId": 10,
"title": "test",
"body": "bla bla"
}

### create new user - using the json-server
POST http://{{host}}/api/json-server/users HTTP/1.1
Content-Type: application/json

{
  "email": "george2.bluth@reqres.in",
  "first_name": "George2",
  "last_name": "Bluth2",
  "avatar": "https://reqres.in/img/faces/1-image.jpg"
}

### create new album - using the jsonplaceholder api
POST http://{{host}}/api/jsonplaceholder/albums HTTP/1.1
Content-Type: application/json

{
  "userId": 1,
  "title": "test album"
}

###
GET http://{{host}}/api/jsonplaceholder/albums HTTP/1.1
Content-Type: application/json

### create new photo - using the jsonplaceholder api
POST http://{{host}}/api/jsonplaceholder/photos HTTP/1.1
Content-Type: application/json

{
  "albumId": 1,
  "title": "test",
  "url": "https://via.placeholder.com/600/92c952",
  "thumbnailUrl": "https://via.placeholder.com/150/92c952"
}